notifications:
        email: false
        irc:
                channels:
                        - "irc.rizon.net#gtorrent"
                on_success: always
                on_failure: always

install:
        # Install dependancies
        - scripts/deps.sh
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
        
language: cpp

compiler:
        - gcc
        - clang

script:
        - scripts/install.sh
