language: cpp

compiler:
  - gcc
  - clang

notifications:
        email: false
        irc:
                channels:
                        - "irc.rizon.net#gtorrent"
                on_success: always
                on_failure: always
        template:
                - "%{repository_slug}/%{branch} (%{commit} - %{author}): %{message}"
                - "Change view : %{compare_url}"
                - "Build details: %{build_url}"
                - "Result: %{result}"

cache: apt

install:
        # Install dependancies
        - scripts/deps.sh
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90

script:
        - scripts/install.sh
