notifications:
        email: false

        irc:
                channels:
                        - "irc.rizon.net#gtorrent"
                on_success: always
                on_failure: always

before_install:
        - sudo apt-add-repository -y ppa:ubuntu-toolchain-r/test
        - sudo apt-get update -q && sudo apt-get dist-upgrade
install:
        - sudo apt-get install -qy cmake libgtkmm-3.0-dev libglibmm-2.4-dev libtorrent-rasterbar-dev libboost-dev g++-4.8 gcc-4.8
        - sudo update-alternatives --install /usr/bin/g++ g++ /usr/bin/g++-4.8 90
language: cpp
compiler:
        - gcc
        - clang

          # Change this to your needs
script: ./install.sh
